<?php
require("inc/inc.init.php");
if( AUTH_ADMIN===true ) {;;} else die();

include("inc/inc.header.php");

// Empty variables

$id = '';
$username = '';
$password = '';
$firstname = '';
$lastname = '';
$email = '';
$auth = '';


// -------------------------
// Save a user
// -------------------------
if($_POST['act']=='save')
{

	// get the posted values
	$id = $_POST['id'];
	$username = trim($_POST['username']);
	$firstname = trim($_POST['firstname']);
	$lastname = trim($_POST['lastname']);
	$email = trim($_POST['email']);

	$ok_to_save = true;

	if( !ereg("^[A-Za-z0-9_\.\-]+$", $username, $res) )
	{
		$message = "Only A-Z, a-z, underscore, period and minussign are allowed in username.";
		$ok_to_save = false;
	}

	 // calculate new auth value
	$auth = $_SESSION['sess_auth'];
	foreach($USER_RIGHTS as $arr) // uncheck all current USER_RIGHTS bits. Resets are done again below.
	{
		$auth = $bits->unsetBit($auth, $arr['bit']);
	}
	foreach($_POST as $nam=>$val) // re-set chosen bits again.
	{
		if(strpos($nam,'userright')!==false) { $auth = $bits->setBit( $auth, substr($nam,10)); }
	}


	// save as new user
	if($_POST['id']=='' && $username != '' && $email != '' && $ok_to_save === true)
	{
		$auth = $bits->setBit($auth, BIT_CHANGEPASS);
		$keychars = "abcdefghijklmnopqrstuvwxyz0123456789";
		$length = 10;
		$randkey = "";
		$max=strlen($keychars)-1;
		for ($i=0;$i<=$length;$i++) {
		  $randkey .= substr($keychars, rand(0, $max), 1);
		}
		$password = md5($randkey);

		$sql = sprintf("INSERT INTO users (username, password, firstname, lastname, email, auth) VALUES('%s','%s','%s','%s','%s','%d')",
			$username, $password, $firstname, $lastname, $email, $auth);
		if(!mysql_query($sql, $db)) { $message = 'user not created - '.mysql_error(); } 
		else 
		{ 
			$to  = "$email";
			$subject = "aspect system message";
			
			$message = '<html><head><title>aspect system message</title></head><body>';
			$message.= '<p>A new user has been created for you.</p>';
			$message.= '<p>username: '.$username.'<br>password: '.$randkey.'</p>';
			$message.= '<p style="color:red">You cannot reply to this mail since it was autogenerated</p>';
			$message.= '</body></html>';	

			$headers  = "MIME-Version: 1.0\r\n";
			$headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
			$headers .= "To: $firstname <$email>\r\n";
			$headers .= "From: aspect <NO-REPLY@localhost.aspect>\r\n";
	
			if(mail($to, $subject, $message, $headers)) $message = "User created and mail sent.";
			else $message = "User created but mail could NOT be sent.";
		}
	}

	// save by updating the user
	else if($username != '' && $email != '' && $ok_to_save === true)
	{
		$sql = sprintf("UPDATE users SET username='%s', firstname='%s', lastname='%s', email='%s', auth='%d' WHERE id='%d'", 
			$username, $firstname, $lastname, $email, $auth, $id);
		if(!mysql_query($sql, $db)) { $message = 'user not updated'; } else { $message = 'User updated'; }
	}
	else if($message == '') $message = 'User not saved/updated. Check fields!';
}

// -------------------------
// Delete a user
// -------------------------
if($_POST['act']=='delete')
{
	// get the posted values
	$id = $_POST['id'];

	if($id!='')
	{
		$sql = sprintf("DELETE FROM users WHERE id='%d'", $id);
		if(!mysql_query($sql, $db)) { $message = 'user not deleted'; } else { $message = 'User deleted'; }
	}
}

// -------------------------
// Load a user
// -------------------------
if($_GET['load']!='' || $_POST['act']=='mail')
{
	$id = $_GET['load'] == '' ? $_POST['id'] : $_GET['load'];

	$sql = sprintf("SELECT * FROM users WHERE id='%d' ORDER BY username", $id );
	$qry = mysql_query($sql, $db);
	if($user = mysql_fetch_array($qry))
	{
		$id = $user['id'];
		$username = $user['username'];
		$password = $user['password'];
		$firstname = $user['firstname'];
		$lastname = $user['lastname'];
		$email = $user['email'];
		$auth = $user['auth'];
	}
}


// -------------------------
// Re-mail a user
// -------------------------
if($_POST['act']=='mail')
{
	if($id!='')
	{
		$keychars = "abcdefghijklmnopqrstuvwxyz0123456789";
		$length = 10;
		$randkey = "";
		$max=strlen($keychars)-1;
		for ($i=0;$i<=$length;$i++) {
		  $randkey .= substr($keychars, rand(0, $max), 1);
		}
		$password = md5($randkey);
		$auth = $bits->setBit($auth, BIT_CHANGEPASS);

		$sql = sprintf("UPDATE users SET password='%s', auth='%d' WHERE id='%d'", $password, $auth, $id);
		if(!mysql_query($sql, $db)) { $message = 'user not updated'; } 
		else { 
			$to  = "$email";
			$subject = "aspect system message";
			
			$message = '<html><head><title>aspect system message</title></head><body>';
			$message.= '<p>A new password has been created for you.</p>';
			$message.= '<p>username: '.$username.'<br>password: '.$randkey.'</p>';
			$message.= '<p style="color:red">You cannot reply to this mail since it was autogenerated</p>';
			$message.= '</body></html>';	

			$headers  = "MIME-Version: 1.0\r\n";
			$headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
			$headers .= "To: $firstname <$email>\r\n";
			$headers .= "From: aspect <NO-REPLY@localhost.aspect>\r\n";

			if(mail($to, $subject, $message, $headers)) $message = "Password generated and new mail sent";
			else $message = "Failure in sending mail, but password is updated";
		}
	}
}


?>

<?php // = FORM START ========== ?>

<form name="useradmin" method="post" action="useradmin.php">
<input type="hidden" name="id" value="<?php echo $id?>">
<input type="hidden" name="act" value="">

<br>
<p class="flerp2">Create new, edit or delete user</p>
<br>

<table border="0" cellspacing="0" cellpadding="4">
	<tr>
		<th class="r">username</th>
		<td><input type="text" name="username" value="<?php echo $username?>"><?php req();?></td>
	</tr>
	<tr>
		<th class="r">e-mail</th>
		<td><input type="text" name="email" value="<?php echo $email?>"><?php req();?></td>
	</tr>
	<tr>
		<th class="r">first name</th>
		<td><input type="text" name="firstname" value="<?php echo $firstname?>"></td>
	</tr>
	<tr>
		<th class="r">last name</th>
		<td><input type="text" name="lastname" value="<?php echo $lastname?>"></td>
	</tr>
	<tr>
		<th class="r">user id</th>
		<td>&nbsp;<?php echo  $id==''?'NEW USER':$id;?></td>
	</tr>
	<tr>
		<th class="r">user rights</th>
		<td>
			<?php
			$bits = new bits();
			foreach($USER_RIGHTS as $arr)
			{
				$checked = $bits->checkBit($auth, $arr['bit']) ? 'checked' : '';
				?>
				<input type="checkbox" class="chkbox" name="userright-<?php echo $arr['bit']?>" <?php echo $checked?>><?php echo $arr['desc']?><br>
				<?php
			}
			?>
		</td>
	</tr>
	<tr>
		<th class="r">&nbsp;</th>
		<td>
			<input type="submit" class="btn" id="btnclear" value="clear" onclick="this.form.id.value=''" onMouseOver="LightOn(this)" onMouseOut="LightOff(this)">

			<?php if($id=='') { $disabled = 'disabled'; $savetext = 'save'; } else { $savetext = 'save'; } ?>

			<input <?php echo $disabled?> type="submit" class="btn<?php echo $disabled?>" id="btndel" value="delete" onclick="if( confirm('Are you sure?')) {this.form.act.value='delete'} else {return false;}" onMouseOver="LightOn(this)" onMouseOut="LightOff(this)">
			<input <?php echo $disabled?> type="submit" class="btn<?php echo $disabled?>" id="btnmail" value="re-mail" onclick="if( confirm('Are you sure?')) {this.form.act.value='mail'} else {return false;}" onMouseOver="LightOn(this)" onMouseOut="LightOff(this)">


			<input type="submit" class="btn" id="btnsave" value="<?php echo $savetext?>" onclick="this.form.act.value='save'" onMouseOver="LightOn(this)" onMouseOut="LightOff(this)">
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td><?php if($message!='') echo '<p class="notice">'.$message.'</p>'; ?>&nbsp;</td>
	</tr>

</table>
</form>
<?php // = FORM END ========== ?>

<br><br>
<p class="flerp">Load existing user</p>
<br>
<?php
$sql = sprintf("SELECT id,username FROM users ORDER BY username");
$qry = mysql_query($sql, $db);
while($users = mysql_fetch_array($qry))
{
	echo "::&nbsp;<a href=\"useradmin.php?load=".$users['id']."\">".$users['username']."</a>&nbsp;&nbsp;";
}
?>
<?php
include("inc/inc.footer.php");
?>
